context:
  version: "0.1.5"

package:
  name: py-rust-stemmers
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/p/py-rust-stemmers/py_rust_stemmers-${{ version }}.tar.gz
    sha256: e9c310cfb5c2470d7c7c8a0484725965e7cab8b1237e106a0863d5741da3e1f7
  - url: https://raw.githubusercontent.com/qdrant/py-rust-stemmers/refs/heads/master/LICENSE
    sha256: f79ad92c0936186de30f349d55f5e4162845793661e5f8b4d07e8734a92fed6a

build:
  number: 3
  skip:
    - match(python, ">=3.14")

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - maturin
    - if: build_platform != target_platform
      then:
        - python
        - pip
        - cross-python_${{ target_platform }}
  host:
    - python
    - pip
    - maturin
  run:
    - python

tests:
  - if: build_platform == target_platform
    then:
      python:
        imports:
          - py_rust_stemmers
        pip_check: true
  - if: build_platform == target_platform
    then:
      script:
        - python -c "from py_rust_stemmers import SnowballStemmer; s = SnowballStemmer('english'); assert s.stem_word('running') == 'run'"

about:
  homepage: https://github.com/qdrant/py-rust-stemmers
  summary: Fast and parallel snowball stemmer
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - moritzwilksch
