context:
  version: 0.1.3

package:
  name: py-rust-stemmers
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/p/py-rust-stemmers/py_rust_stemmers-${{ version }}.tar.gz
    sha256: ad796d47874181a25addb505a04245e34620bd7a0c5055671f52d9ce993253e2
  - url: https://raw.githubusercontent.com/qdrant/py-rust-stemmers/refs/heads/master/LICENSE
    sha256: f79ad92c0936186de30f349d55f5e4162845793661e5f8b4d07e8734a92fed6a

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin
  run:
    - python

tests:
  - python:
      imports:
        - py_rust_stemmers
      pip_check: true

about:
  homepage: https://github.com/qdrant/py-rust-stemmers
  summary: Fast and parallel snowball stemmer
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - moritzwilksch
